
services:
  # Database
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: swcotizador5440
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - swcotizador-network 
  # Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3010:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: production
      
      STAGE: ${STAGE}

      PORT: ${PORT}
      HOST_API: ${HOST_API}

      JWT_SECRET: ${JWT_SECRET}

      PAYPAL_URL: ${PAYPAL_URL}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}

      CLOUD_NAME_CLOUDINARY: ${CLOUD_NAME_CLOUDINARY}
      API_KEY_CLOUDINARY: ${API_KEY_CLOUDINARY}
      API_SECRET_CLOUDINARY: ${API_SECRET_CLOUDINARY}
      FOLDER_CLOUDINARY: ${FOLDER_CLOUDINARY}
      CLOUDINARY_PRESET: ${CLOUDINARY_PRESET}

      API_KEY_GPT: ${API_KEY_GPT}
    depends_on:
      - db
    container_name: swcotizador_backend
    networks:
      - swcotizador-network

networks:
  swcotizador-network:
    driver: bridge
    external: true